### ISSUE TITLE
Problems loading data and running examples

### ISSUE THREAD

**Issue by Kamuish** [pmaxted/pycheops#59] opened 2019-10-28 14:05 UTC
Hello,

I am working with @sousasag and need to fit planet's parameters for the CHEOPS's light curves. I have attempted to use your project and I have found some problems so far. 

All of those problems appear when using the examples provided in the notebooks:

notebook: TestTransitModel

1.   File "<home folder>/pycheops/pycheops/models.py", line 507, in factor
    cos2phi = self.sinphi(t)**2 - self.cosphi(t)**2
TypeError: 'NoneType' object is not callable

Assuming that I am not misinterpreting anything (i.e. cosphi is not a function that calculates the cos but, instead, is a list with values) you should have sinphi[t]. Moreso, the same could be said for dx and dy, which appear to be functions

Aside from that, the real problem is when the default value of None is passed inside the function.  

notebook:dataset_fit_transit_from_simulation

1) when using: Dataset().from_simulation(7649, target='HD97658')
 
     -    File "teste_2.py", line 8, in <module>
    dataset = Dataset().from_simulation(7649, target='HD97658')
TypeError: __init__() missing 1 required positional argument: 'file_key'

2)   when using: dataset = Dataset('CH_PR900048_TG001501')
       -   File "/home/andre/archi/pycheops/pycheops/dataset.py", line 181, in __init__
    raise ValueError('Invalid file_key {}'.format(file_key))
ValueError: Invalid file_key CH_PR900048_TG001501

3)   when using: dataset=Dataset.from_test_data('DP-079', target='HD97658')
  File "/home/andre/archi/pycheops/pycheops/dataset.py", line 278, in from_test_data
    m = _dataset_re.search(file_key)
NameError: name '_dataset_re' is not defined

**Comment by ThomasGWilson** [comment] 2019-10-28 14:22
Hi Kamuish,

I've been working a bit with PyCheops and I think I can help. Recently, Pierre has updated the code to take data from the DACE archive (https://dace.unige.ch/cheopsDatabase/). At least the 2nd point in the 2nd set of problems you mention can be solved by calling Dataset('CH_PR900048_TG001501_V0000'). This is because PyCheops now identifies the data using the full file_key. I think this is also the cause of 1) and 3) in your Dataset script as the code doesn't recognise either "7649" or "HD97658" as a file_key.

As for your model issue I think this is an issue with the self.sinphi(t) and self.cosphi(t) arrays. I think I had the same problem before, but without seeing the whole code I'm not sure. Try using this code to make the sinphi(t) and cosphi(t) code:

        time = np.array(self.lc['time'])
        phi = self.lc['roll_angle']*np.pi/180
        sinphi = InterpolatedUnivariateSpline(time,np.sin(phi))
        cosphi = InterpolatedUnivariateSpline(time,np.cos(phi))

Thanks,
Tom

**Comment by Kamuish** [comment] 2019-10-28 14:54
Hi ThomasGWilson

I had to remove the DACE module ( I do not have an account), but I have checked that the code does not enter the part in which it is used. That first solution appears to be working, thanks for that.

Regarding your comment on the model, if I am understanding properly, you suggest to make some changes to the library, which is not a great idea, especially for compatibility reasons. Just to be clear, I am running the code straigth from the notebook example, without any changes. I will try to dig a little deeper and report back

**Comment by Kamuish** [comment] 2019-10-28 15:04
Hello,

I managed to run pycheops, although when loading data from a local data set, the dataset "target" stays as "simulation" and thus, to allow the StarProperties class to initialize you have to manually put the target name, i.e. pHD97658 = StarProperties('HD97658')

I will keep this issue open until @pmaxted  sees it.

Thanks for your help,
André

**Comment by ThomasGWilson** [comment] 2019-10-28 15:11
Hi Andre,

Good to hear that it has worked. Just so I understand, did this fix the error from model.py?

Thanks,
Tom

**Comment by Kamuish** [comment] 2019-10-28 16:49
Hi,

I have not implemented your changes of changing the internal behaviour of pycheops. When using the dataset class I can now perform the fits.

I have looked a little bit deeper into the source code and what I found was (when running this exact notebook)
        -  if you print the keyword arguments, in line 821 ( "eval" function in the model.py file) you see that the
               -     self.make_funcargs(params, kwargs)['dfdcos2phi'] takes the value 1.4901161193880158e-08 before the error occurs.
      - This value, != 0 leads to the condition, from line 506 from the models.py file to be evaluated to True
             -             if dfdcos2phi != 0 :
                cos2phi = self.sinphi(t)**2 - self.cosphi(t)**2
                trend += dfdcos2phi*cos2phi

     - At this point in time, the self.sinphi variable is still None, thus triggering the error

I don't know enough about the internal workings of pycheops to solve this. I believe that this problem either comes from a step that does not occurs when using the library without the dataset class or a problem with the notebook example. 

Cheers,
André

**Comment by ThomasGWilson** [comment] 2019-10-28 17:10
Hi Andre,

Try changing the 3rd cell of the TestTransitModel to:

    m = FactorModel()*TransitModel()
    pars = m.make_params(T_0=T_0, D=D, W=W, S=S, h_1=h_1, h_2=h_2, c=c)
    pars['P'].set(value=P, vary=False)
    pars['f_c'].set(value=0, vary=False)
    pars['f_s'].set(value=0, vary=False)
    pars['h_2'].set(vary=False)
    pars['dfdcos2phi'].set(vary=False)
    pars['dfdsin2phi'].set(vary=False)
    pars

Note the 2 new lines for the 2nd and 3rd to last lines. This works for me now, whilst I was getting the same errors as you before when I didn't included those 2 new lines.

Thanks,

Tom

**Comment by ThomasGWilson** [comment] 2019-10-28 17:17
Looking deeper into this, this appears to have occurred because 'dfdcos2phi' and 'dfdsin2phi' are not included in the conditional of the 'for' statements on lines 518/519 and 527/528 of models.py:

        for p in ['dfdx', 'dfdy', 'd2fdx2', 'd2fdxdy',  'd2fdy2', 
                  'dfdsinphi', 'dfdcosphi', 'dfdt', 'd2fdt2']:

Which allows these variables to vary and trigger the 'if' statements  that you were running into. Therefore, these lines need to be updated.

Thanks,
Tom

**Comment by Kamuish** [comment] 2019-10-28 20:24
Hello,

setting those "extra" lines managed to correct the problems. I have not tested your proposed changes to the models.py, but your reasoning appears to be correct. Should either of us make a pull request or should we wait for the developer to say something?

Thanks for your help,
André

**Comment by ThomasGWilson** [comment] 2019-10-28 20:41
Hi Andre,

No worries, happy to help, and glad we got it fixed. I'm sure Pierre will see this chat, but regardless I'll email him and mention this bug.

Thanks,
Tom

**Comment by pmaxted** [comment] 2019-11-01 15:07
Thanks for these bug reports and fixes. This should not all be fixed in version 0.5.0

**Closed by pmaxted** 2019-11-01 15:07 UTC
